name: Publish Site

on:
  workflow_dispatch:
  push:
    branches:
     - main
    paths:
      - '**.qmd'
      - '**.yml'
      - '**.css'
      - '**.scss'

jobs:
  publish:
    name: Build & Deploy Quarto Projects
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Render Quarto Project
        run: quarto render --output-dir _site
        shell: bash

      - name: Publish Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true
