name: Publish Site

on:
  workflow_dispatch:
  push:
    branches:
     - main
    paths:
      - '**.qmd'
      - '**.yml'
      - '**.css'
      - '**.scss'

jobs:
  publish:
    name: Build & Deploy Site
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Render Quarto Project
        run: quarto render --output-dir _site
        shell: bash

      - name: Publish Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true

  broken_link_checker_job:
    runs-on: ubuntu-latest
    needs: publish
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.2
        with:
          # Required:
          url: "https://phuse-org.github.io/devops/"
          # optional:
          honorRobotExclusions: false
          ignorePatterns: "github,google"
          recursiveLinks: false # Check all URLs on all reachable pages (could take a while)
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
